# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-22 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_remove_kirrurl_shortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirrurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
